name: Filetype Check (FORBIDDEN patterns only)
description: Fails if committed files match FORBIDDEN patterns from central-gitignore.txt

inputs:
  rules-url:
    description: "URL to central-gitignore.txt"
    required: false
    default: "https://raw.githubusercontent.com/AmsterdamUMC-test/org-security-workflows/main/central-gitignore.txt"
  telemetry-url:
    description: "Optional REST API endpoint to receive telemetry JSON"
    required: false
    default: ""
  telemetry-token:
    description: "Optional bearer/API token for the telemetry endpoint"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Download central gitignore
      shell: bash
      run: |
        curl -sL "${{ inputs.rules-url }}" -o central-gitignore.txt

    - name: Extract FORBIDDEN patterns
      shell: bash
      run: |
        # Extract blocked and exception patterns separately
        awk '
          /^# BEGIN FORBIDDEN/ { capture=1; next }
          /^# END FORBIDDEN/   { capture=0; next }
          capture && /^[^#]/ && NF { print }
        ' central-gitignore.txt > forbidden-patterns.txt

        echo "Extracted forbidden patterns:"
        cat forbidden-patterns.txt

    - name: Check all tracked files
      shell: bash
      env:
        TELEMETRY_URL: ${{ inputs.telemetry-url }}
        TELEMETRY_TOKEN: ${{ inputs.telemetry-token }}
      run: |
        set -uo pipefail

        STATUS="ok"
        MESSAGE="no_forbidden_patterns"
        BLOCKED=0
        BLOCKED_FILES=()

        if [[ ! -s forbidden-patterns.txt ]]; then
          echo "No FORBIDDEN patterns found, skipping check"
        else
          # Parse patterns into blocked and exceptions
          BLOCKED_PATTERNS=()
          EXCEPTION_PATTERNS=()

          while IFS= read -r line; do
            [[ -z "$line" ]] && continue
            if [[ "$line" == !* ]]; then
              EXCEPTION_PATTERNS+=("${line#!}")
            else
              BLOCKED_PATTERNS+=("${line}")
            fi
          done < forbidden-patterns.txt

          # Function to check if filename matches a glob pattern
          matches_pattern() {
            local file="$1"
            local pattern="$2"
            local basename="${file##*/}"

            if [[ "$pattern" == \** ]]; then
              [[ "$basename" == $pattern ]] && return 0
            elif [[ "$pattern" == .* ]]; then
              [[ "$basename" == $pattern ]] && return 0
            elif [[ "$basename" == "$pattern" ]]; then
              return 0
            fi
            return 1
          }

          while IFS= read -r FILE; do
            is_blocked=false
            is_exception=false

            # Check if file matches any blocked pattern
            for pattern in "${BLOCKED_PATTERNS[@]}"; do
              if matches_pattern "$FILE" "$pattern"; then
                is_blocked=true
                break
              fi
            done

            # If blocked, check if it's an exception
            if [[ "$is_blocked" == true ]]; then
              for pattern in "${EXCEPTION_PATTERNS[@]}"; do
                if matches_pattern "$FILE" "$pattern"; then
                  is_exception=true
                  break
                fi
              done
            fi

            # Add to blocked list if blocked and not an exception
            if [[ "$is_blocked" == true && "$is_exception" == false ]]; then
              echo "::error file=$FILE::Blocked by FORBIDDEN patterns in central-gitignore.txt"
              BLOCKED_FILES+=("$FILE")
              BLOCKED=1
            fi
          done < <(git ls-files)

          if [[ $BLOCKED -eq 1 ]]; then
            echo ""
            echo "=========================================="
            echo "ERROR: Forbidden file types detected!"
            echo "=========================================="
            echo "Blocked files:"
            for f in "${BLOCKED_FILES[@]}"; do
              echo "  - $f"
            done
            echo ""
            echo "These files must be removed from the repository."
            echo "See: https://github.com/AmsterdamUMC-test/org-security-workflows#remediation"
            STATUS="fail"
            MESSAGE="forbidden_files_found"
          else
            echo "No forbidden file types found."
            STATUS="ok"
            MESSAGE="no_forbidden_files"
          fi
        fi

        # ---------- Telemetry ----------
        if [[ -n "${TELEMETRY_URL:-}" ]]; then
          echo "Sending telemetry to $TELEMETRY_URL"

          # Build JSON array of blocked files
          BLOCKED_JSON="["
          first=true
          for f in "${BLOCKED_FILES[@]}"; do
            if [[ "$first" == true ]]; then
              first=false
            else
              BLOCKED_JSON+=","
            fi
            # Escape any quotes in filename
            escaped_f="${f//\"/\\\"}"
            BLOCKED_JSON+="\"${escaped_f}\""
          done
          BLOCKED_JSON+="]"

          # Build payload using jq for proper JSON encoding
          PAYLOAD=$(cat <<EOF
{
  "repository": "${GITHUB_REPOSITORY:-unknown}",
  "workflow": "${GITHUB_WORKFLOW:-unknown}",
  "run_id": "${GITHUB_RUN_ID:-unknown}",
  "run_number": "${GITHUB_RUN_NUMBER:-unknown}",
  "sha": "${GITHUB_SHA:-unknown}",
  "ref": "${GITHUB_REF:-unknown}",
  "actor": "${GITHUB_ACTOR:-unknown}",
  "status": "${STATUS}",
  "message": "${MESSAGE}",
  "blocked_files": ${BLOCKED_JSON},
  "timestamp": "$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
}
EOF
)

          # Build curl command with optional auth header
          CURL_ARGS=(-sS -X POST "$TELEMETRY_URL" -H "Content-Type: application/json")
          if [[ -n "${TELEMETRY_TOKEN:-}" ]]; then
            CURL_ARGS+=(-H "Authorization: Bearer ${TELEMETRY_TOKEN}")
          fi

          # Fire-and-forget: telemetry failure must NOT break the check
          if curl "${CURL_ARGS[@]}" -d "$PAYLOAD" --max-time 10; then
            echo "Telemetry sent successfully."
          else
            echo "::warning::Telemetry send failed (ignored)."
          fi
        else
          echo "No telemetry-url configured; skipping telemetry."
        fi
        # ---------- End telemetry ----------

        exit $BLOCKED