name: Filetype Check (FORBIDDEN patterns only)
description: Fails if committed files match FORBIDDEN patterns from central-gitignore.txt

inputs:
  rules-url:
    description: "URL to central-gitignore.txt"
    required: false
    default: "https://raw.githubusercontent.com/AmsterdamUMC-test/org-security-workflows/main/central-gitignore.txt"
  telemetry-pat:
    description: "PAT with repo scope for sending telemetry via repository dispatch"
    required: false
    default: ""
  telemetry-repo:
    description: "Repository to receive telemetry (e.g., AmsterdamUMC-test/security-telemetry)"
    required: false
    default: "AmsterdamUMC-test/security-telemetry"

runs:
  using: "composite"
  steps:
    - name: Download central gitignore
      shell: bash
      run: |
        curl -sL "${{ inputs.rules-url }}" -o central-gitignore.txt

    - name: Extract FORBIDDEN patterns
      shell: bash
      run: |
        awk '
          /^# BEGIN FORBIDDEN/ { capture=1; next }
          /^# END FORBIDDEN/   { capture=0; next }
          capture && /^[^#]/ && NF { print }
        ' central-gitignore.txt > forbidden-patterns.txt

        echo "Extracted forbidden patterns:"
        cat forbidden-patterns.txt

    - name: Check all tracked files
      id: check
      shell: bash
      run: |
        set -uo pipefail

        STATUS="ok"
        MESSAGE="no_forbidden_patterns"
        BLOCKED=0
        BLOCKED_FILES=()

        if [[ ! -s forbidden-patterns.txt ]]; then
          echo "No FORBIDDEN patterns found, skipping check"
        else
          BLOCKED_PATTERNS=()
          EXCEPTION_PATTERNS=()

          while IFS= read -r line; do
            [[ -z "$line" ]] && continue
            if [[ "$line" == !* ]]; then
              EXCEPTION_PATTERNS+=("${line#!}")
            else
              BLOCKED_PATTERNS+=("${line}")
            fi
          done < forbidden-patterns.txt

          matches_pattern() {
            local file="$1"
            local pattern="$2"
            local basename="${file##*/}"

            if [[ "$pattern" == \** ]]; then
              [[ "$basename" == $pattern ]] && return 0
            elif [[ "$pattern" == .* ]]; then
              [[ "$basename" == $pattern ]] && return 0
            elif [[ "$basename" == "$pattern" ]]; then
              return 0
            fi
            return 1
          }

          while IFS= read -r FILE; do
            is_blocked=false
            is_exception=false

            for pattern in "${BLOCKED_PATTERNS[@]}"; do
              if matches_pattern "$FILE" "$pattern"; then
                is_blocked=true
                break
              fi
            done

            if [[ "$is_blocked" == true ]]; then
              for pattern in "${EXCEPTION_PATTERNS[@]}"; do
                if matches_pattern "$FILE" "$pattern"; then
                  is_exception=true
                  break
                fi
              done
            fi

            if [[ "$is_blocked" == true && "$is_exception" == false ]]; then
              echo "::error file=$FILE::Blocked by FORBIDDEN patterns in central-gitignore.txt"
              BLOCKED_FILES+=("$FILE")
              BLOCKED=1
            fi
          done < <(git ls-files)

          if [[ $BLOCKED -eq 1 ]]; then
            echo ""
            echo "=========================================="
            echo "ERROR: Forbidden file types detected!"
            echo "=========================================="
            echo "Blocked files:"
            for f in "${BLOCKED_FILES[@]}"; do
              echo "  - $f"
            done
            echo ""
            echo "These files must be removed from the repository."
            echo "See: https://github.com/AmsterdamUMC-test/org-security-workflows#remediation"
            STATUS="fail"
            MESSAGE="forbidden_files_found"
          else
            echo "No forbidden file types found."
            STATUS="ok"
            MESSAGE="no_forbidden_files"
          fi
        fi

        # Export for next step
        echo "status=${STATUS}" >> "$GITHUB_OUTPUT"
        echo "message=${MESSAGE}" >> "$GITHUB_OUTPUT"
        echo "blocked=${BLOCKED}" >> "$GITHUB_OUTPUT"

        # Save blocked files to a file for the next step
        printf '%s\n' "${BLOCKED_FILES[@]}" > blocked_files.txt

    - name: Send telemetry via repository dispatch
      if: ${{ inputs.telemetry-pat != '' }}
      uses: actions/github-script@v7
      env:
        STATUS: ${{ steps.check.outputs.status }}
        MESSAGE: ${{ steps.check.outputs.message }}
        TELEMETRY_REPO: ${{ inputs.telemetry-repo }}
      with:
        github-token: ${{ inputs.telemetry-pat }}
        script: |
          const fs = require('fs');

          // Read blocked files
          let blockedFiles = [];
          try {
            const content = fs.readFileSync('blocked_files.txt', 'utf8');
            blockedFiles = content.split('\n').filter(f => f.trim() !== '');
          } catch (e) {
            // No blocked files
          }

          const [owner, repo] = process.env.TELEMETRY_REPO.split('/');

          await github.rest.repos.createDispatchEvent({
            owner: owner,
            repo: repo,
            event_type: 'security_alert',
            client_payload: {
              repository: process.env.GITHUB_REPOSITORY,
              run_id: process.env.GITHUB_RUN_ID,
              sha: process.env.GITHUB_SHA,
              ref: process.env.GITHUB_REF,
              actor: process.env.GITHUB_ACTOR,
              status: process.env.STATUS,
              blocked_files: blockedFiles,
              timestamp: new Date().toISOString()
            }
          });

          console.log('Telemetry sent to ' + process.env.TELEMETRY_REPO);

    - name: No telemetry configured
      if: ${{ inputs.telemetry-pat == '' }}
      shell: bash
      run: |
        echo "No telemetry-pat configured; skipping telemetry."

    - name: Exit with appropriate code
      shell: bash
      run: |
        exit ${{ steps.check.outputs.blocked }}
