name: Filetype Check (central gitignore)
description: Fails if files match forbidden patterns defined in central-gitignore.txt

inputs:
  rules-url:
    description: "URL to central gitignore ruleset"
    required: false
    default: "https://raw.githubusercontent.com/bavadeve/org-security-workflows/main/central-gitignore.txt"

runs:
  using: "composite"
  steps:
    - name: Download central gitignore
      shell: bash
      run: |
        curl -sL "${{ inputs.rules-url }}" -o central-gitignore.txt

    - name: Check all tracked files
      shell: bash
      run: |
        BLOCKED=0
        while IFS= read -r FILE; do
          git -c core.excludesfile=central-gitignore.txt check-ignore -q "$FILE"
          if [[ $? -eq 0 ]]; then
            echo "::error file=$FILE::Blocked by central gitignore rules"
            BLOCKED=1
          fi
        done < <(git ls-files)

        exit $BLOCKED
